version: '3'
services:
  mongo_db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - './data:/data/db'
  back:
    build: ./LOCALIB_BACK
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongo_db
  front:
    build: ./LOCALIB_FRONT
    ports:
      - 3000:3000
